language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '8'
  - '7'
  - '6'
script:
  - npm run prepush
    # get the coverage metrics to coveralls
  - npm run coveralls-report
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
